packages:
  - "apps/*"
  - "packages/*"

# 공통으로 사용되는 패키지 버전 관리
catalog:
  # 코어 라이브러리
  "typescript": "^5.5.4"
  "next": "^15.3.0"
  "eslint": "^9.0.0"
  "eslint-config-next": "^15.3.0"
  "@eslint/eslintrc": "^3.0.0"
  "@types/node": "^20.11.24"
  
  # 데이터 관리 라이브러리
  "zod": "^3.23.8"
  "zustand": "^5.0.1"
  "immer": "^10.1.1"
  
  # 유틸리티
  "cookies-next": "^5.0.2"
  "axios": "^1.7.8"
  
  # 빌드 도구
  "tsup": "^8.1.0"
  "vite": "^5.3.4"
  "vite-tsconfig-paths": "^4.3.2"
  "@vitejs/plugin-react": "^4.3.1"
  
  # 테스트 도구
  "vitest": "^1.6.1"
  "happy-dom": "^16.8.1"
  "@testing-library/jest-dom": "^6.6.3"
  "@testing-library/react": "^16.2.0"
  "@vitest/coverage-v8": "^1.3.1"
  
  # CSS 도구
  "tailwindcss": "^4.0.0"
  "postcss": "^8.4.49"
  "autoprefixer": "^10.4.20"
  "@tailwindcss/postcss": "^4.0.0"
  
  # 폼 관련
  "react-hook-form": "^7.53.2"
  "@hookform/resolvers": "^3.9.1"

# 리액트 버전별 카탈로그
catalogs:
  # React 18
  react18:
    "react": "^18.3.1"
    "react-dom": "^18.3.1"
    "@types/react": "^18.3.12"
    "@types/react-dom": "^18.3.1"

  # React 19
  react19:
    "react": "^19.0.0"
    "react-dom": "^19.0.0"
    "@types/react": "^19.0.0"
    "@types/react-dom": "^19.0.0"
  
  # React Query
  react-query5:
    "@tanstack/react-query": "^5.62.0"
    "@tanstack/react-query-devtools": "^5.62.0"
